---
# tasks file for imbicile.nfs

- name: create nds directory
  file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: 0644
  loop: "{{ nfs_foldes }}"
  when: nfs_foldes_create

- name: install nfs
  apt:
    name:
      - nfs-common
      - nfs-kernel-server
    state: present

- name: copy exports
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: reload exportfs

- name: nfs is running
  service:
    name: nfs-kernel-server.service
    enabled: yes
    state: started
